# --- logins schema
# --- To avoid constraint name conflict
# --- constraint_xxx were added to the CONSTRAINT name
# --- generated by MySQLWorkBench EER Model

# --- !Ups
CREATE TABLE IF NOT EXISTS `LOGINS` (
  `provider` INT NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`provider`, `key`),
  INDEX `key_idx` (`key` ASC),
  CONSTRAINT `constraint_login_provider`
    FOREIGN KEY (`provider`)
    REFERENCES `PROVIDERS` (`provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `constraint_login_key`
    FOREIGN KEY (`key`)
    REFERENCES `USERS` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

# --- !Downs

DROP TABLE `LOGINS`;
