# --- authenticators schema
# --- To avoid constraint name conflict
# --- constraint_XXX were added to the CONSTRAINT name
# --- generated by MySQLWorkBench EER Model


# --- !Ups
CREATE TABLE IF NOT EXISTS `AUTHENTICATORS` (
  `provider` INT NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  `lastUsed` DATETIME NULL,
  `expiration` DATETIME NULL,
  `idleTimeOut` INT NULL,
  `duration` INT NULL,
  INDEX `key_idx` (`key` ASC),
  PRIMARY KEY (`provider`, `key`),
  CONSTRAINT `constraint_authenticator_provider`
    FOREIGN KEY (`provider`)
    REFERENCES `LOGINS` (`provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `constraint_authenticator_key`
    FOREIGN KEY (`key`)
    REFERENCES `LOGINS` (`key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

# --- !Downs

DROP TABLE `AUTHENTICATORS`;
